name: Jazz Drive Remote Bot

on:
  workflow_dispatch: # Button se chalaein

jobs:
  remote_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # ðŸ”¥ Yeh step bot ko super fast bana dega
      - name: Cache Playwright
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright

      - name: Install Tools
        run: |
          pip install playwright pyTelegramBotAPI requests
          playwright install chromium

      - name: Run Remote Bot
        run: |
          python upload.py
